version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns: ["*"]
        exclude-patterns:
          - "syn"
          - "sqlx"
          - "bcrypt"
    open-pull-requests-limit: 10
