[workspace]

[[package]]
name = "interceptors"
release = false

[[package]]
name = "sword-web-example"
release = false

[[package]]
name = "sword-grpc-example"
release = false

[[package]]
name = "sword-socketio-example"
release = false

[[package]]
name = "sword-web-tests"
release = false
publish = false

[[package]]
name = "sword-grpc-tests"
release = false
publish = false

[[package]]
name = "sword-socketio-tests"
release = false
publish = false
