[application]
name = "SocketIO Application Example"
graceful-shutdown = false

[web]
host = "0.0.0.0"
port = 8081
body-limit = "5MB"

[socketio]
parser = "common"
transports = ["websocket", "polling"]

[tracing]
enabled = true
default-filter = "info,sword=info"
format = "pretty"
time-style = "none"
with-fields = []
