[application]
name = "gRPC Application Example"
graceful-shutdown = true

[grpc]
host = "0.0.0.0"
port = 50051

[grpc.body-limit]
max-decoding-message-size = "2 MiB"
max-encoding-message-size = "2 MiB"

[tracing]
enabled = true
filter = "info,sword=info"
format = "dev"
time-style = "none"
time-pattern = "%H:%M:%S"
with-fields = []
