[application]
name = "Web Application Example"
graceful-shutdown = false

[web]
host = "0.0.0.0"
port = 8081
body-limit = "5MB"
request-timeout = { enabled = true, timeout = "15s" }

[tracing]
enabled = true
default-filter = "info,sword=debug,sqlx=error"
format = "dev"
time-style = "none"
with-fields = []

[database]
uri = "${POSTGRES_DATABASE_URL}"
migrations_path = "config/migrations"

[hasher]
cost = 12
